version: '3.8'

services:
  # Aplikasi Flask kita
  web:
    build: .
    environment:
      - FLASK_APP=app.py
    networks:
      - backend-net
    depends_on:
      - redis

  # Redis sebagai database hitungan
  redis:
    image: "redis:alpine"
    networks:
      - backend-net

  # Nginx sebagai pintu depan
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
